language: php

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - 'hhvm'

matrix:
  fast_finish: true
  allow_failures:
    - php: '5.3'
    - php: '5.4'
    - php: 'hhvm'

before_script:
  - composer self-update
  - composer require --dev escapestudios/symfony2-coding-standard:~2.0
  - composer require fabpot/php-cs-fixer
  - composer install
  - vendor/bin/phpcs --config-set installed_paths vendor/escapestudios/symfony2-coding-standard

script:
  - vendor/bin/phpcs -ps --colors --standard=Symfony2 --ignore=vendor/*,Tests/*,App/ACF/* --extensions=php ./
  - phpunit --coverage-clover clover.xml

notifications:
  - email: robert@sayenkodesign.com