key: "group_theme_options"
title: "Theme Options"
location:
  -
    - { param: "options_page", operator: "==", value: "acf-options-theme-options" }
menu_order: 0
position: "normal"
style: "default"
label_placement: "top"
instruction_placement: label
hide_on_screen: ""
fields:
  -
    key:  "field_57d9b0cfe4c9f"
    label:  "Google Analytics ID"
    name:  "google_analytics_id"
    type:  "text"
    instructions:  ""
    required:  0,
    conditional_logic:  0,
    wrapper:  { width:  "", class:  "", id:  "" }
    default_value:  ""
    placeholder:  ""
    prepend:  ""
    append:  ""
    maxlength:  ""
    readonly:  0,
    disabled:  0
  -
    key:  "field_57d9c7b4d5985"
    label:  "Logo"
    name:  "logo"
    type:  "image"
    instructions:  ""
    required:  1
    conditional_logic:  0
    wrapper:  {width:  "25", class:  "", id:  "" }
    return_format:  "array"
    preview_size:  "thumbnail"
    library:  "all"
    min_width:  ""
    min_height:  ""
    min_size:  ""
    max_width:  ""
    max_height:  ""
    max_size:  ""
    mime_types:  ""
  -
    key:  "field_57d9c7d4d5986"
    label:  "Alt Logo"
    name:  "alt_logo"
    type:  "image"
    instructions:  ""
    required:  0
    conditional_logic:  0
    wrapper:  { width:  "25", class:  "", id:  "" }
    return_format:  "array"
    preview_size:  "thumbnail"
    library:  "all"
    min_width:  ""
    min_height:  ""
    min_size:  ""
    max_width:  ""
    max_height:  ""
    max_size:  ""
    mime_types:  ""
  -
    key:  "field_57d9c7e5a615f"
    label:  "Mobile Logo"
    name:  "mobile_logo"
    type:  "image"
    instructions:  ""
    required:  1
    conditional_logic:  0
    wrapper:  { width:  "25", class:  "", id:  "" }
    return_format:  "array"
    preview_size:  "thumbnail"
    library:  "all"
    min_width:  ""
    min_height:  ""
    min_size:  ""
    max_width:  ""
    max_height:  ""
    max_size:  ""
    mime_types:  ""
  -
    key:  "field_57d9c7f3a6160"
    label:  "Favicon"
    name:  "favicon"
    type:  "image"
    instructions:  ""
    required:  0
    conditional_logic:  0
    wrapper:  { width:  "25", class:  "", id:  "" }
    return_format:  "array"
    preview_size:  "thumbnail"
    library:  "all"
    min_width:  ""
    min_height:  ""
    min_size:  ""
    max_width:  ""
    max_height:  ""
    max_size:  ""
    mime_types:  ""
